# Follow network settings are used to assign ip to vpn client
# and accesses are limited by
# https://github.com/jenkins-infra/jenkins-infra/blob/production/dist/profile/manifests/openvpn.pp
networks:
  private:
    iprange: 10.9.0.0/24 # dmz subnet which holds the principal network interface of the VPN VM
    netmask: 255.255.255.0
    routes:
      # TODO: track with updatecli from https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json
      private: 10.248.0.0/14
      # TODO: track with updatecli from https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json
      private-sponsored: 10.240.0.0/14
      # TODO: track with updatecli from https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json
      public: 10.244.0.0/14
      # TODO: track with updatecli from https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json
      public-db: 10.253.0.0/21
      # TODO: add manually to users whom require access to this instance (JenSec, Infra)
      # TODO: track with updatecli from https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json
      cert.ci.jenkins.io: 10.252.8.0/21
      # TODO: add manually to users whom require access to this instance (JenSec, Infra)
      # TODO: track with updatecli from https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json
      trusted.ci.jenkins.io: 10.252.0.0/21
      # TODO: track with updatecli (Digital Ocean)
      archives.jenkins.io: 46.101.121.132/32
      # TODO: track with updatecli (AWS CloudBees)
      pkg.origin.jenkins.io: 52.202.51.185/32
      # TODO: track with updatecli (AWS CloudBees)
      usage.jenkins.io: 52.204.62.78/32
      # TODO: track with updatecli (AWS CloudBees)
      census.jenkins.io: 52.202.38.86/32
      # TODO: track with updatecli from https://reports.jenkins.io/jenkins-infra-data-reports/azure.json
      azure.ci.jenkins.io: 172.200.138.43/32
